In [144]:
import numpy as np
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt

In [145]:
listings_filepath = '/Users/arneshsaha/Desktop/AirBnb/datasets/listings.csv'
listings_df = pd.read_csv(listings_filepath)
listings_df.head(5)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,15420.0,https://www.airbnb.com/rooms/15420,2.022120e+13,16/12/2022,city scrape,Georgian Boutique Apt City Centre,"Stunning, spacious ground floor apartment minu...","The neighbourhood is in the historic New Town,...",https://a0.muscache.com/pictures/cf69631f-4194...,60423,...,4.98,4.98,4.91,NaN,f,1,1,0,0,3.10
1,707097.0,https://www.airbnb.com/rooms/707097,2.022120e+13,16/12/2022,city scrape,Centre Royal Mile Apartment 3 bedrooms 2 bathr...,NaN,"The location is the perfect for tourism , shor...",https://a0.muscache.com/pictures/6e2ded8d-f20b...,3092851,...,4.72,4.94,4.09,NaN,t,8,6,2,0,0.55
2,728199.0,https://www.airbnb.com/rooms/728199,2.022120e+13,16/12/2022,city scrape,"Private room in central, spacious and comfy flat",Fantastic main door flat over two levels withi...,"Great location for access to the city centre, ...",https://a0.muscache.com/pictures/11315577/0091...,3776412,...,4.97,4.73,4.79,NaN,f,1,0,1,0,2.86
3,732008.0,https://www.airbnb.com/rooms/732008,2.022120e+13,16/12/2022,city scrape,51 18 Caledonian Crescent,This beautiful third floor apartment is set in...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,3810279,...,4.81,4.71,4.70,NaN,t,2,2,0,0,2.27
4,744710.0,https://www.airbnb.com/rooms/744710,2.022120e+13,16/12/2022,city scrape,Refurbished Flat in a Georgian Era Building in...,A stunning apartment in the heart of Edinburgh...,The apartment is in a Central Edinburgh neighb...,https://a0.muscache.com/pictures/monet/Select-...,3737047,...,4.96,4.96,4.86,NaN,t,1,1,0,0,1.73

Data Cleaning

1. neighbourhood_group_cleansed (Check if the whole column is empty)

In [146]:
columns = ['host_url', 'host_name', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'calendar_updated', 'calendar_last_scraped','picture_url', 'neighbourhood_group_cleansed','license']
listings_df.drop(columns=columns, inplace=True)
listings_df.head(5)

,id,name,description,neighborhood_overview,host_id,host_since,host_location,host_about,host_response_time,host_response_rate,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,15420.0,Georgian Boutique Apt City Centre,"Stunning, spacious ground floor apartment minu...","The neighbourhood is in the historic New Town,...",60423,06/12/2009,"Edinburgh, United Kingdom","I have a background in property, having worked...",within a few hours,100%,...,4.97,4.98,4.98,4.91,f,1,1,0,0,3.10
1,707097.0,Centre Royal Mile Apartment 3 bedrooms 2 bathr...,NaN,"The location is the perfect for tourism , shor...",3092851,29/07/2012,"Edinburgh, United Kingdom",Airbnb partner owner . Will do my best to make...,within a day,50%,...,4.69,4.72,4.94,4.09,t,8,6,2,0,0.55
2,728199.0,"Private room in central, spacious and comfy flat",Fantastic main door flat over two levels withi...,"Great location for access to the city centre, ...",3776412,06/10/2012,"Edinburgh, United Kingdom",We are an early/mid 40's couple who love to tr...,within an hour,100%,...,4.95,4.97,4.73,4.79,f,1,0,1,0,2.86
3,732008.0,51 18 Caledonian Crescent,This beautiful third floor apartment is set in...,NaN,3810279,09/10/2012,"London, United Kingdom",We are a family run business specialising in h...,within an hour,100%,...,4.84,4.81,4.71,4.70,t,2,2,0,0,2.27
4,744710.0,Refurbished Flat in a Georgian Era Building in...,A stunning apartment in the heart of Edinburgh...,The apartment is in a Central Edinburgh neighb...,3737047,02/10/2012,"Edinburgh, United Kingdom",I'm Gareth and I own and manage this gem of a ...,within an hour,100%,...,4.93,4.96,4.96,4.86,t,1,1,0,0,1.73

In [147]:
listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7389 entries, 0 to 7388
Data columns (total 64 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            7389 non-null   float64
 1   name                                          7389 non-null   object
 2   description                                   7318 non-null   object
 3   neighborhood_overview                         5184 non-null   object
 4   host_id                                       7389 non-null   int64
 5   host_since                                    7389 non-null   object
 6   host_location                                 6067 non-null   object
 7   host_about                                    4292 non-null   object
 8   host_response_time                            5861 non-null   object
 9   host_response_rate                            5861 non-null   object
 10  host_acceptance_rate                          6663 non-null   object
 11  host_is_superhost                             7387 non-null   object
 12  host_thumbnail_url                            7389 non-null   object
 13  host_picture_url                              7389 non-null   object
 14  host_neighbourhood                            3007 non-null   object
 15  host_listings_count                           7389 non-null   int64
 16  host_total_listings_count                     7389 non-null   int64
 17  host_verifications                            7389 non-null   object
 18  host_has_profile_pic                          7389 non-null   object
 19  host_identity_verified                        7389 non-null   object
 20  neighbourhood                                 5184 non-null   object
 21  neighbourhood_cleansed                        7389 non-null   object
 22  latitude                                      7389 non-null   float64
 23  longitude                                     7389 non-null   float64
 24  property_type                                 7389 non-null   object
 25  room_type                                     7389 non-null   object
 26  accommodates                                  7389 non-null   int64
 27  bathrooms                                     0 non-null      float64
 28  bathrooms_text                                7376 non-null   object
 29  bedrooms                                      7251 non-null   float64
 30  beds                                          7284 non-null   float64
 31  amenities                                     7389 non-null   object
 32  price                                         7389 non-null   object
 33  minimum_nights                                7389 non-null   int64
 34  maximum_nights                                7389 non-null   int64
 35  minimum_minimum_nights                        7389 non-null   int64
 36  maximum_minimum_nights                        7389 non-null   int64
 37  minimum_maximum_nights                        7389 non-null   int64
 38  maximum_maximum_nights                        7389 non-null   int64
 39  minimum_nights_avg_ntm                        7389 non-null   float64
 40  maximum_nights_avg_ntm                        7389 non-null   float64
 41  has_availability                              7389 non-null   object
 42  availability_30                               7389 non-null   int64
 43  availability_60                               7389 non-null   int64
 44  availability_90                               7389 non-null   int64
 45  availability_365                              7389 non-null   int64
 46  number_of_reviews                             7389 non-null   int64
 47  number_of_reviews_ltm                         7389 non-null   int64
 48  number_of_reviews_l30d                        7389 non-null   int64
 49  first_review                                  6724 non-null   object
 50  last_review                                   6724 non-null   object
 51  review_scores_rating                          6724 non-null   float64
 52  review_scores_accuracy                        6711 non-null   float64
 53  review_scores_cleanliness                     6711 non-null   float64
 54  review_scores_checkin                         6711 non-null   float64
 55  review_scores_communication                   6711 non-null   float64
 56  review_scores_location                        6711 non-null   float64
 57  review_scores_value                           6711 non-null   float64
 58  instant_bookable                              7389 non-null   object
 59  calculated_host_listings_count                7389 non-null   int64
 60  calculated_host_listings_count_entire_homes   7389 non-null   int64
 61  calculated_host_listings_count_private_rooms  7389 non-null   int64
 62  calculated_host_listings_count_shared_rooms   7389 non-null   int64
 63  reviews_per_month                             6724 non-null   float64
dtypes: float64(16), int64(21), object(27)
memory usage: 3.6+ MB

Modification
<p>8. Removing the HTML Tags from description</p>

In [148]:
from bs4 import BeautifulSoup
# define a function to remove HTML tags from a string
def remove_html_tags(text):
    if pd.isna(text):
        return text
    soup = BeautifulSoup(text, 'html.parser')
    return soup.get_text()

# apply the function to the "description" column
listings_df['description'] = listings_df['description'].apply(remove_html_tags)

# print the updated dataframe
listings_df['description']

/var/folders/rv/l0bvb2qx7kj9z133h3zxt1040000gn/T/ipykernel_12774/3168537498.py:6: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(text, 'html.parser')

0       Stunning, spacious ground floor apartment minu...
1                                                     NaN
2       Fantastic main door flat over two levels withi...
3       This beautiful third floor apartment is set in...
4       A stunning apartment in the heart of Edinburgh...
                              ...
7384    The spaceLocated just off McDonald Road, Paper...
7385    The spaceRoom over looking the Pentland Hill  ...
7386    The spaceDario is a new modern apartment minut...
7387    On the doorstep of Arthur's Seat and Holyrood ...
7388    The SpaceSituated in a quiet Mews courtyard, t...
Name: description, Length: 7389, dtype: object

<p>7. Seperate parking from description/name</p>

In [149]:
parking_rows = listings_df[(listings_df['name'].str.contains('parking', case=False)) | 
                           (listings_df['amenities'].apply(lambda x: 'parking' in x))]
parking_rows

,id,name,description,neighborhood_overview,host_id,host_since,host_location,host_about,host_response_time,host_response_rate,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,15420.0,Georgian Boutique Apt City Centre,"Stunning, spacious ground floor apartment minu...","The neighbourhood is in the historic New Town,...",60423,06/12/2009,"Edinburgh, United Kingdom","I have a background in property, having worked...",within a few hours,100%,...,4.97,4.98,4.98,4.91,f,1,1,0,0,3.10
1,707097.0,Centre Royal Mile Apartment 3 bedrooms 2 bathr...,NaN,"The location is the perfect for tourism , shor...",3092851,29/07/2012,"Edinburgh, United Kingdom",Airbnb partner owner . Will do my best to make...,within a day,50%,...,4.69,4.72,4.94,4.09,t,8,6,2,0,0.55
2,728199.0,"Private room in central, spacious and comfy flat",Fantastic main door flat over two levels withi...,"Great location for access to the city centre, ...",3776412,06/10/2012,"Edinburgh, United Kingdom",We are an early/mid 40's couple who love to tr...,within an hour,100%,...,4.95,4.97,4.73,4.79,f,1,0,1,0,2.86
3,732008.0,51 18 Caledonian Crescent,This beautiful third floor apartment is set in...,NaN,3810279,09/10/2012,"London, United Kingdom",We are a family run business specialising in h...,within an hour,100%,...,4.84,4.81,4.71,4.70,t,2,2,0,0,2.27
4,744710.0,Refurbished Flat in a Georgian Era Building in...,A stunning apartment in the heart of Edinburgh...,The apartment is in a Central Edinburgh neighb...,3737047,02/10/2012,"Edinburgh, United Kingdom",I'm Gareth and I own and manage this gem of a ...,within an hour,100%,...,4.93,4.96,4.96,4.86,t,1,1,0,0,1.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7383,361050.0,Large room in disabled friendly flat - Bruntsf...,In fantastic Bruntsfield with its individual s...,You can walk to Princes Street and the Univers...,1825119,28/02/2012,"Edinburgh, United Kingdom",I am a retired teacher who now works part time...,within a few hours,100%,...,5.00,4.99,4.92,4.90,f,1,0,1,0,0.62
7384,362653.0,"Papermill Wynd Chiara Apartment,","The spaceLocated just off McDonald Road, Paper...",NaN,1775021,19/02/2012,"Gourock, United Kingdom","I am 56 years old, married with two children, ...",within a few hours,100%,...,4.74,4.77,4.51,4.59,f,4,3,1,0,0.33
7385,363642.0,Wonderful/beautiful room Edinburgh,The spaceRoom over looking the Pentland Hill ...,Close to the city centre. But surrounded by g...,1837147,01/03/2012,"Edinburgh, United Kingdom","I have lived in Edinburgh all my life, and kno...",within an hour,100%,...,4.92,4.92,4.62,4.74,f,1,0,1,0,0.54
7386,376937.0,"Dario Apartment, Edinburgh",The spaceDario is a new modern apartment minut...,NaN,1775021,19/02/2012,"Gourock, United Kingdom","I am 56 years old, married with two children, ...",within a few hours,100%,...,4.78,4.81,4.62,4.58,f,4,3,1,0,0.63
7387,388297.0,Stunning villa by Holyrood Park -parking & gar...,On the doorstep of Arthur's Seat and Holyrood ...,NaN,1942840,17/03/2012,"Edinburgh, United Kingdom",Hiâ€¦ Iâ€™m a friendly and sociable female & I liv...,within an hour,100%,...,4.92,4.91,4.66,4.77,f,3,3,0,0,0.74

Creating a new column in dataframe, 'Parking', containing 0/1 based on whether the property has Parking space for the customer

In [150]:
listings_df['Parking'] = 0
listings_df.loc[parking_rows.index, 'Parking'] = 1

<p>6. Finding unique values in room_type
</p>

In [151]:
room_type_counts = listings_df['room_type'].value_counts()
room_type_counts

Entire home/apt    5172
Private room       2170
Hotel room           32
Shared room          15
Name: room_type, dtype: int64

In [152]:
room_type_labels, room_type_unique = pd.factorize(listings_df['room_type'])

# replace the property type text with the assigned labels
listings_df['room_type_num'] = room_type_labels
print(room_type_labels)
print(room_type_unique)
listings_df.to_csv('/Users/arneshsaha/Desktop/AirBnb/datasets/cleaned.csv')

[0 0 1 ... 0 0 1]
Index(['Entire home/apt', 'Private room', 'Shared room', 'Hotel room'], dtype='object')

<p>5. Finding unique values in property_type
</p>

In [153]:
property_type_counts = listings_df['property_type'].value_counts()
property_type_counts

Entire rental unit                    3078
Entire condo                          1358
Private room in rental unit            784
Private room in condo                  582
Entire home                            307
Private room in home                   299
Private room in townhouse              147
Entire serviced apartment              127
Entire townhouse                        83
Private room in bed and breakfast       83
Room in boutique hotel                  75
Room in hotel                           48
Private room in guesthouse              41
Entire guest suite                      37
Entire cottage                          36
Private room in bungalow                28
Entire vacation home                    26
Room in hostel                          22
Private room in casa particular         20
Room in aparthotel                      20
Entire loft                             20
Private room in hostel                  19
Entire guesthouse                       18
Entire bungalow                         18
Camper/RV                               15
Entire villa                            12
Shared room in hostel                   12
Private room in guest suite             12
Private room in cottage                  8
Tiny home                                7
Private room in villa                    7
Private room in serviced apartment       5
Private room in loft                     5
Private room in vacation home            4
Room in serviced apartment               4
Entire place                             3
Private room                             3
Private room in tiny home                2
Hut                                      2
Boat                                     2
Entire cabin                             2
Entire chalet                            1
Windmill                                 1
Barn                                     1
Campsite                                 1
Shared room in rental unit               1
Shared room in condo                     1
Shared room in vacation home             1
Farm stay                                1
Name: property_type, dtype: int64

<p>From the value_count, my observations:
    <ol>
        <li>I notice that there are 3 places which have been listed under the property_type 'Entire Place' which is very similar to 'Entire Rental Unit'. I think we should merge '..Place' into '...Unit'. This will help us deal with outliers</li> <br>
        <li>At the end of the list I notice that there are certain places, which are very unique like 'Windmill', 'Barn', etc. which just have only 1-3 propeerties listed under them. We can either delete these properties (For outliers), or we could also determine if having an unique property helps in gaining more 'ratings', 'earnings', etc. </li>
    </ol>
</p>

<p>4. Remove % symbols
        <ul>
            <li>host_acceptance_rate</li>
            <li>host_response_rate</li>
        </ul>
<p>

In [154]:
listings_df['host_acceptance_rate'] = listings_df['host_acceptance_rate'].str.replace('%', '')
listings_df['host_response_rate'] = listings_df['host_response_rate'].str.replace('%', '')
listings_df